spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/pass_batch
    username: root
    password: wjd@568099
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  batch:
    jdbc:
      initialize-schema: always # batch ???? ??????.
